### ISSUE TITLE
Issues With Agduard

### ISSUE THREAD

**Issue by iamLazyCode** [tawhidmonowar/WebCapture#49]
Hi Dev i have 2 issues going on with this great project when using adguard i cant open any webpage

<img src="https://github.com/user-attachments/assets/ba46a993-d462-406b-bc6a-2bbb48698747" alt="" width="" height="350">

then if i stop using adguard see how the original page has different colors to differentiate sections

<img src="https://github.com/user-attachments/assets/4f471232-715c-4b6d-bf03-5e27381636e7" alt="" width="" height="350">

and this is how it converts it all colors are gone

<img src="https://github.com/user-attachments/assets/d513b294-5732-49fc-a0f6-fb8167ac310c" alt="" width="" height="350">

here is the link if you wana test [Intel](https://en.wikipedia.org/wiki/Intel_Quick_Sync_Video#Hardware_decoding_and_encoding)

**Comment by tawhidmonowar** [comment]
Thanks, @iamLazyCode! I’ll look into this issue. I really appreciate your contribution.

**Comment by iamLazyCode** [comment]
> Thanks, @iamLazyCode! I’ll look into this issue. I really appreciate your contribution.

i really hope this project goes along way brother , after this gets fixed il shoot some coffees your way :)

**Comment by tawhidmonowar** [comment]
Hi @iamLazyCode , a new version [ v1.0.3](https://github.com/tawhidmonowar/WebCapture/releases/tag/1.0.3) is out! Issues are fixed, the new **_"YouTube Capture"_** feature is added, and the design is improved. Check it out! Looking forward to a virtual coffee soon ☕️😄

**Comment by iamLazyCode** [comment]
> Hi @iamLazyCode , a new version [ v1.0.3](https://github.com/tawhidmonowar/WebCapture/releases/tag/1.0.3) is out! Issues are fixed, the new **_"YouTube Capture"_** feature is added, and the design is improved. Check it out! Looking forward to a virtual coffee soon ☕️😄

Wont back down on the coffee brother but still test the link i sent...this area is still not colored 

![Screenshot_20250203_083445_Print Spooler.png](https://github.com/user-attachments/assets/11dc1944-2433-4746-8720-f78397ad45f7)

**Comment by tawhidmonowar** [comment]
![Image](https://github.com/user-attachments/assets/be7402b4-c501-4768-aff3-699efe3d68b4)

While saving, you can choose color options, but for this link, it doesn’t seem to be working. 🤔 I'm not sure why, as both Firefox and Chrome are also unable to print it in color.

**Comment by iamLazyCode** [comment]
> ![Image](https://github.com/user-attachments/assets/be7402b4-c501-4768-aff3-699efe3d68b4)
> 
> While saving, you can choose color options, but for this link, it doesn’t seem to be working. 🤔 I'm not sure why, as both Firefox and Chrome are also unable to print it in color.

Please try more to a problem there cant be just 1 solution brother i have faith in you :)
